ubuntu@ubuntu:~$ sudo vi /etc/netplan/00-installer-config.yaml
network:
  renderer: networkd
  ethernets:
    eth0:
      addresses:
        - 192.168.1.49/24
      nameservers:
        addresses: [4.2.2.2, 8.8.8.8]
      routes:
        - to: default
          via: 192.168.1.254

  version: 2